### ISSUE TITLE
rpp++ - missing macOS build

### ISSUE THREAD

**Issue by Z6543** [epi052/osed-scripts#24]
The script assumes that its running on Linux, e.g. it downloads https://github.com/0vercl0k/rp/releases/download/v2-beta/rp-lin-x64

Unfortunately, the updated https://github.com/0vercl0k/rp/tree/next branch does not have official macOS binaries. The old master branch is pretty outdated and lacks features. 

One solution could be to check the OS platform before download, and if it is macOS, use the macOS build. 
I can provide the binary if needed, and can be hosted in this repo.

**Comment by epi052** [comment]
that sounds good to me :+1: 
- detect OS
- download from here or rp++, depending

**Comment by epi052** [comment]
The author just dropped v2, with a macho build. Idk about feature parity / if the interface is still the same, etc etc 

https://github.com/0vercl0k/rp/releases/tag/v2?s=09

**Comment by epi052** [comment]
fixed in #25
